<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <meta http-equiv="x-ua-compatible" content="ie=edge" />
  <title>Product View</title>
</head>

<body>
  <!--Main Navigation-->

  <!-- Products -->
  <section>
    <div class="container my-5">
      <header class="mb-4">
        <h3>Searched Books</h3>
      </header>
      <div class="row" id="main_display">
        <?php
        echo $main;
        ?>
      </div>
    </div>
  </section>
  <!-- Products -->

</body>
<!-- Custom scripts -->
<script type="text/javascript" src="./JS/script.js"></script>

</html>
